language: node_js

node_js:
  - "11.10.1"

cache: yarn

script:
  - yarn test
  - yarn build

deploy:
  - provider: npm
    skip-cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
      repo: rmarganti/ts-json-api

  - provider: npm
    skip-cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    tag: next
    on:
      branch: next
      tags: true
      repo: rmarganti/ts-json-api
